import soccer1 from "./assets/images/soccer-1.jpeg";
import soccer2 from "./assets/images/soccer-2.jpeg";
import soccer3 from "./assets/images/soccer-3.jpeg";
import soccer4 from "./assets/images/soccer-4.jpeg";
export const FakeData = [
  {
    id: 1,
    name: "Product 1",
    price: 19.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 2,
    name: "Product 2",
    price: 29.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 3,
    name: "Product 3",
    price: 39.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 4,
    name: "Product 1",
    price: 19.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 5,
    name: "Product 2",
    price: 29.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 6,
    name: "Product 3",
    price: 39.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 7,
    name: "Product 1",
    price: 19.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 8,
    name: "Product 2",
    price: 29.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 9,
    name: "Product 3",
    price: 39.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 10,
    name: "Product 1",
    price: 19.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 11,
    name: "Product 2",
    price: 29.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
  {
    id: 12,
    name: "Product 3",
    price: 39.99,
    imageUrl: soccer1,
    image1: soccer4,
    image2: soccer2,
  },
];
