/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      animation: {
        "spin-slow": "spin 3s linear infinite",
      },
      fontFamily: {
        orbitron: ["Orbitron", "sans-serif"],

        sans: ["Inter", "sans-serif"],
      },
      colors: {
        base: "var(--base)",
        default: "var(--default)",
        divider: "var(--divider)",
        dividers: "var(--dividers)",
        disabled: "var(--disabled)",
        disabledbutton: "var(--disabled-button)",
        disabledtext: "var(--disabled-text)",
        elevation: "var(--elevation)",
        hinttext: "var(--hint-text)",
        textsecondary: "var(--text-secondary)",
        icon: "var(--icon)",
        icons: "var(--icons)",
        text: "var(--text)",
        slidermin: "var(--slider-min)",
        slideroff: "var(--slider-off)",
        slideroffactive: "var(--slider-off-active)",
        statusbar: "var(--status-bar)",
        appbar: "var(--app-bar)",
        background: "var(--background)",
        hover: "var(--hover)",
        card: "var(--card)",
        dialog: "var(--dialog)",
        disabledbutton: "var(--disabled-button)",
        raisedbutton: "var(--raised-button:)",
        focusedbutton: "var(--focused-button)",
        selectedbutton: "var(--selected-button)",
        selecteddisabledbutton: "var(--selected-disabled-button)",
        disabledbuttontoggle: "var(--disabled-button-toggle:)",
        unselectedchip: "var(--unselected-chip)",
        disabledlistoption: "var(--disabled-list-option)",
        tooltip: "var(--tooltip)",
        textall: "var(--textall)",
      },
    },
  },
  plugins: [],
};
